version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        depends_on: #mongo is gonna start 1st
            - mongo
            - redis
            - nginx
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=jamm3e3333 
            - MONGO_INITDB_ROOT_PASSWORD=ahoj123
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis
        
volumes:
    mongo-db: