version: "3"
services: 
    node-app:
        build:
            context: .
            args: 
                NODE_ENV: development
        volumes:
            - ./:/src
            - /src/node_modules
        environment: 
            - NODE_ENV=development
        env_file:
            - ./config/dev.env
        command: npm run dev

    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=jamm3e3333 
            - MONGO_INITDB_ROOT_PASSWORD=ahoj123
