version: "3"
services:
    nginx:
        ports:
            - "80:80"
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
            - PORT=${PORT}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_IP=${DB_IP}
            - DB_PORT=${DB_PORT}
            - REDIS_URL=${REDIS_URL}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_SECRET=${REDIS_SECRET}
        command: node index.js
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}