version: "3"
services: 
    node-app:
        build:
            context: .
            args: 
                NODE_ENV: development
        volumes:
            - ./:/src
            - /src/node_modules
        environment: 
            - NODE_ENV=development
        env_file:
            - ./dev.env
        command: npm run dev

