version: "3"
services: 
    node-app:
        build: .
        ports:
            - "3000:3000"
        depends_on: #mongo is gonna start 1st
            - mongo
            - redis
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=jamm3e3333 
            - MONGO_INITDB_ROOT_PASSWORD=ahoj123
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis
        
volumes:
    mongo-db: