version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
        env_file:
            - ./prod.env
        command: node index.js